### ISSUE TITLE
Add support for .NET Core?

### ISSUE THREAD

**Issue by sdcb** [jstedfast/Portable.Text.Encoding#4]
Since it's already support UWP, supporting .NET Core should not be very hard.

**Comment by jstedfast** [comment]
This shouldn't be needed for .NET core.

**Comment by sdcb** [comment]
Why not?
ASP.NET Core is based on .NET Core with only a few encoding (like UTF-8) supported. Handling some encoding like GB2312 is very tricky when using CoreCLR.

**Comment by jstedfast** [comment]
You need to reference https://www.nuget.org/packages/System.Text.Encoding.CodePages/4.0.1-beta-23516

**Comment by sdcb** [comment]
I'm sorry and thank you very much!

**Comment by jstedfast** [comment]
no prob
