### ISSUE TITLE
Compilation fails without installing portable class library reference assemblies

### ISSUE THREAD

**Issue by ethus3h** [jstedfast/Portable.Text.Encoding#5]
This package does not compile for me, apparently because I don't have the portable class library reference assemblies installed. How can I compile it without them? I can't find source code for them, so installing them is not an option.

[Here's a build log, containing the relevant error message.](https://gist.github.com/ethus3h/0c696059014377a308b617ba445de4d5)

Thanks.

**Comment by jstedfast** [comment]
You need to install them. There's no other option.

**Comment by ethus3h** [comment]
I see, I guess I'll see if my app can run with the libraries that require the reference assemblies commented out. Thanks for the info.
